image:  reaverproject/gcc-boost:latest

before_script:
    - apt-get update -qq && apt-get install -y -qq libboost-all-dev
    - cd build
    - cmake ..

build:
    stage: build
    script:
        - pwd
        - make
