image:  reaverproject/gcc-boost:7_4_0-1.69.0

before_script:
    - apt-get install -y -qq cmake libsfml-dev
    - cd build
    - cmake ..

build:
    stage: build
    script:
        - pwd
        - make
